// твой возраст;
let yourAge = 25;
// год рождения;
let yourYear_of_Birth = 1997;
// число рождения (без нолика в начале);
let birthNumber = 16;
// количество родных братьев;
let number_of_brothers = 1;
// количество родных сестер;
let number_of_sisters = 1;
// количество человек в семье;
let number_of_familyЬembers = 5;
// стоимость проезда до места обучения;
let fare = 28;
// текущий год;
let thisYear = 2022;
// курс доллара;
let dollarExchangeRate = 61.79;
// курс евро;
let euroExchangeRate = 61.18;
// курс биткоина;
let bitcoinRate = 20489.30;

// текущий год минус год рождения;
let ageСalculation = 2022 - 1997;
// текущий год минус твой возраст;
let yearСalculation = 2022 - 25;
// количество родных братьев плюс количество родных сестер;
let number_of_siblings = 1 - 1;
// курс евро умноженный на 1000;
let euroPerThousand = 61.18 * 1000;
// курс доллара умноженный на 2.5;
let dollartwo_fifths = 61.79 * 2.5;
// курс биткоина разделенный на 10000;
let bitcoinDividedIntoThousands = 20489.30 / 1000;
// стоимость проезда до места обучения разделенная на курс доллара;
let fareDividedByDollar = 28 / 61.79;
// количество человек в семье минус количество братьев минус количество сестер;
let family_siblings = 5 - 1 - 1;
// 0 деленный на твой возраст;
let zero_divided_by_age = 0 / 25;
// 35 минус твой возраст;
let number_minus_age = 35 - 28;